## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

### How Numpy is fast ?

The underlying functions are built on C++ which are enabling them for faster execution

In [3]:
## initially Lets import numpy

import numpy as np

In [4]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
## check the shape of the array

arr.shape

(3, 5)

### Indexing 

In [11]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr[2:,:]

array([[9, 7, 6, 8, 9]])

In [17]:
arr1=arr

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [20]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [22]:
arr[3:]=100

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2, 2])

### What if we give row x columns in reshape() which is not equal to array size ?
It will fail, only the row x column combinations that should give the exact size needs to be given

In [25]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
arr1=np.arange(0,10).reshape(2,5)

In [27]:
arr2=np.arange(0,10).reshape(2,5)

In [35]:
print(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [29]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
## random distribution
np.random.rand(3,3)

array([[0.87785986, 0.30643901, 0.87551738],
       [0.34932149, 0.60974069, 0.62173667],
       [0.11491255, 0.02077109, 0.71099948]])

In [31]:
arr_ex=np.random.randn(4,4)

In [32]:
arr_ex

array([[ 1.76804117, -0.77924137, -2.11018574, -0.12129313],
       [-0.00357359,  0.61524327,  1.67084582, -1.45592371],
       [-0.98655132, -0.91331949,  0.30975584, -0.36181958],
       [-0.35677594, -0.03971881,  0.17089595, -1.89681633]])

In [33]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
sns.distplot(pd.DataFrame(arr_ex.reshape(16,1)))

: 

In [ ]:
np.random.randint(0,100,8).reshape(4,2)

: 

In [ ]:
np.random.random_sample((1,5))

: 

: 